encrypt-type: # 0:standard, 1:guomi
  encrypt-type: 0

group-channel-connections-config:
  caCert: classpath:ca.crt
  sslCert: classpath:sdk.crt
  sslKey: classpath:sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        - 127.0.0.1:20200 # node listen_ip:channel_listen_port
        - 127.0.0.1:20201
    - group-id: 2
      connections-str:
        - 127.0.0.1:20202 # node listen_ip:channel_listen_port
        - 127.0.0.1:20203

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  agency-name: fisco # agency name

accounts:
  pem-file: 0xcdcce60801c0a2e6bb534322c32ae528b9dec8d2.pem
  p12-file: 0x98333491efac02f8ce109b0c499074d47e7779a6.p12
  password: 123456

spring:
  data:
    mongodb:
      uri: mongodb://localhost/test
#目的是为了去除thymeleaf严格的校验，不然html界面写的不严谨就会报错
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html

addressconf:
  allPublicAddress: { User: 0x33674063c4618f4773fac75dc2f07e55f6f391ce, Arbitrator: 0x6bc952a2e4db9c0c86a368d83e9df0c6ab481102, Depositor: 0x5a6c7ccf9efa702f4e8888ff7e8a3310abcf8c51 }